name: Hugo workflow build and deploy to S3

on:
  push:
    paths:
      - "content/**"
      - "layouts/**"
      - "static/**"
    branches: [ master ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out master
        uses: actions/checkout@master

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::033617006106:role/github-actions
          role-session-name: GitHubActionsSession
          aws-region: eu-south-2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
            hugo-version: 'latest'

      - name: Build
        run: hugo --minify

      - name: Deploy to S3
        run: hugo deploy --force --maxDeletes -1 --invalidateCDN