name: Hugo workflow build and deploy to S3

on:
  push:
    branches: [ master ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out master
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE }}
          role-session-name: GitHubActionsSession
          aws-region: eu-south-2

      - name: Change directory and create public folder
        run: |
          pwd
          cd recetas-para-sobrevivir
          mkdir public
          ls

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
            hugo-version: 'latest'

      - name: Build
        run: hugo --minify
        working-directory: ./recetas-para-sobrevivir

      - name: Deploy to S3
        run: hugo deploy --force --maxDeletes -1 --invalidateCDN
        working-directory: ./recetas-para-sobrevivir